root = "."
tmp_dir = "cmd/tmp"

[build]
bin = "./cmd/tmp/main.exe"
cmd = "templ generate && go build -o ./cmd/tmp/main.exe ./cmd"
delay = 1000
exclude_dir = ["assets", "tmp", "vendor", "scripts"]
exclude_file = []
exclude_regex = [".*_templ.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = []
include_ext = ["go", "tpl", "tmpl", "templ", "html", "css"]
kill_delay = "0s"
log = "build-errors.log"
send_interrupt = true
stop_on_error = true

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
time = false

[misc]
clean_on_exit = false