// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.778
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Auth() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!doctype html><html lang=\"es\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Login</title><link href=\"/assets/css/output.css\" rel=\"stylesheet\"><script src=\"/vendored/htmx_v2.0.3.min.js\"></script><style>\r\n            /* Estilo adicional para hacer la tabla desplazable */\r\n            .scrollable-table-container {\r\n              max-height: 300px; /* Ajusta la altura máxima según sea necesario */\r\n              overflow-y: auto;\r\n              border: 1px solid #ccc;\r\n              border-radius: 4px;\r\n            }\r\n        </style></head><body><header class=\"bg-green-300 p-4 sticky top-0 z-50\"><div class=\"container mx-auto flex justify-between items-center\"><a class=\"text-black-50 font-bold text-2xl\" href=\"/\">Navix</a></div></header><div class=\"bg-gray-100 flex items-center justify-center min-h-screen\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = LogIn().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div><!-- Footer Section --><footer class=\"bg-green-300 text-black-50 py-6\"><div class=\"container mx-auto text-center\"><p>&copy; 2024 Universidad Tecnologica de Bolivar. Todos los derechos reservados.</p></div></footer></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

func LogIn() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div id=\"auth_window\" class=\"bg-white shadow-md rounded-lg p-8 max-w-md w-full\"><h2 class=\"text-2xl font-bold text-center mb-6 text-gray-800\">Ingresa</h2><!-- Login Form --><form hx-post=\"/login\" hx-target=\"#message\" hx-swap=\"innerHTML\"><div class=\"mb-4\"><label for=\"username\" class=\"block text-gray-700\">Usuario</label> <input type=\"text\" id=\"username\" name=\"username\" required class=\"w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-green-500\"></div><div class=\"mb-3\"><label for=\"password\" class=\"block text-gray-700\">Contraseña</label> <input type=\"password\" id=\"password\" name=\"password\" required class=\"w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-green-500\"></div><div id=\"message\" class=\"text-center text-red-500\"></div><a href=\"/DEMO_MODE\" class=\"w-full text-center bg-green-400 text-white font-semibold py-2 rounded-lg hover:bg-green-500 my-3\">Empieza ya (DEMO MODE)</a><!--\r\n            <button type=\"submit\" hx-get=\"/rot\" hx-target=\"#auth_window\" hx-swap=\"innerHTML\"\r\n                    class=\"w-full bg-green-400 text-white font-semibold py-2 rounded-lg hover:bg-green-500 my-3\">\r\n                Ingresa\r\n            </button>\r\n            --></form><!--Link to Register--><p class=\"text-center text-gray-600 mt-3\">No tienes una cuenta? <button hx-get=\"/register\" hx-target=\"#auth_window\" hx-swap=\"outerHTML\" class=\"text-green-600 hover:underline\">Regístrate</button></p></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

func Register() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div id=\"auth_window\" class=\"bg-white shadow-md rounded-lg p-8 max-w-md w-full\"><h2 class=\"text-2xl font-bold text-center mb-6 text-gray-800\">Registrate</h2><!-- Login Form --><form hx-post=\"/register\" hx-target=\"#message\" hx-swap=\"innerHTML\"><div class=\"mb-4\"><label for=\"username\" class=\"block text-gray-700\">Correo</label> <input type=\"text\" id=\"username\" name=\"username\" required class=\"w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-green-500\"></div><div class=\"mb-3\"><label for=\"password\" class=\"block text-gray-700\">Contraseña</label> <input type=\"password\" id=\"password\" name=\"password\" required class=\"w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-green-500\"></div><div class=\"mb-2\"><label for=\"password\" class=\"block text-gray-700\">Repite Contraseña</label> <input type=\"password\" id=\"password\" name=\"password\" required class=\"w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-green-500\"></div><div id=\"message\" class=\"text-center text-red-500\"></div><button type=\"submit\" class=\"w-full bg-green-400 text-white font-semibold py-2 rounded-lg hover:bg-green-500 my-3\">Completar</button></form><!--Link to Register--><p class=\"text-center text-gray-600 mt-3\">Ya tienes una cuenta? <button hx-get=\"/login\" hx-target=\"#auth_window\" hx-swap=\"outerHTML\" class=\"text-green-600 hover:underline\">Ingresa</button></p></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
