// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.778
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Tables() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"p-4 bg-white flex flex-col items-center min-h-screen\"><div class=\"container mx-auto p-4\"><h1 class=\"text-2xl font-bold text-gray-700 mb-4\">Rutas del Usuario</h1><!-- Tabla de rutas --><div class=\"bg-white shadow-md rounded my-6\"><table class=\"min-w-full table-auto\"><thead><tr class=\"bg-gray-200 text-gray-600 uppercase text-sm leading-normal\"><th class=\"py-3 px-6 text-left\">Origen</th><th class=\"py-3 px-6 text-left\">Destino</th><th class=\"py-3 px-6 text-center\">Estado</th><th class=\"py-3 px-6 text-center\">Acciones</th></tr></thead> <tbody id=\"route-table\" class=\"text-gray-700 text-sm font-light\"><!-- Aquí se insertarán las filas de rutas mediante HTMX --></tbody></table></div><!-- Botón para agregar nueva ruta --><button class=\"bg-blue-500 text-white font-bold py-2 px-4 rounded hover:bg-blue-600 mt-4\" hx-get=\"/new-route\" hx-target=\"#route-table\" hx-swap=\"beforeend\">Agregar Ruta</button></div><!-- Script para manejar el botón de eliminar ruta --><script>\r\n        document.addEventListener(\"htmx:afterOnLoad\", function(event) {\r\n          if (event.detail.elt.classList.contains(\"delete-route\")) {\r\n            event.detail.elt.closest(\"tr\").remove();\r\n          }\r\n        });\r\n      </script></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
